# Generated by Django 4.0.4 on 2022-06-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartender',
            old_name='tipoCoceteleria',
            new_name='tipo_De_Cocteleria',
        ),
    ]
