# Generated by Django 4.0.4 on 2022-06-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0006_rename_tipodecocteleria_bartender_estilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bartender',
            old_name='Estilo',
            new_name='estilo',
        ),
    ]
