# Generated by Django 4.0.4 on 2022-07-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0007_rename_estilo_bartender_estilo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=150)),
            ],
        ),
    ]
