# Generated by Django 4.0.4 on 2022-07-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWeb', '0008_suggestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestions',
            new_name='Suggestion',
        ),
    ]
